name: FSOUNotes
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
# //publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.7+3
  google_sign_in: ^4.5.1
  fluttertoast: ^4.0.1
  flutter_mailer: ^0.5.1
  open_appstore: ^1.0.2
  share: ^0.6.4+3
  intl: ^0.16.1
  font_awesome_flutter: ^8.8.1
  flutter_full_pdf_viewer: ^1.0.6
  path_provider: ^1.6.11
  cuid: ^0.1.2
  shimmer: ^1.1.1
  file_picker: ^1.12.0
  url_launcher: ^5.4.11
  expansion_tile_card: ^1.0.3
  flutter_typeahead: ^1.8.1
  mime: ^0.9.6+3
  awesome_dialog: ^1.1.3



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  stacked: ^1.6.0
  stacked_hooks: 0.1.1+3
  stacked_services: ^0.4.4+1
  logger: ^0.6.0
  # http request
  http: ^0.12.0+2
  # async package to add additional Cancellable operations
  async: ^2.0.8
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  firebase_storage: ^3.1.6
  image_picker: ^0.6.7+2
  cached_network_image: ^2.2.0+1
  firebase_messaging: ^6.0.16
  flutter_auth_buttons: ^0.6.0
  auto_route: ^0.5.0
  modal_progress_hud: ^0.1.3

  get_it:
  injectable:
  flutter_hooks:
  observable_ish:

dev_dependencies:
  flutter_launcher_icons: "^0.7.3"
  flutter_test:
    sdk: flutter

  build_runner:
  auto_route_generator:
  injectable_generator:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/apnaicon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/pdf.png
   - assets/images/pdf1.png
   - assets/images/link.png
   - assets/images/Applogo.jpg
   - assets/images/apnaicon.png
   - assets/images/1.png
   - assets/images/2.png
   - assets/images/3.png
   - assets/images/4.png
   - assets/images/5.png
   - assets/images/6.png
   - assets/images/7.png
   - assets/images/github-logo.png
   - assets/images/OU_Logo.jpg

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
    - family: Custom
      fonts:
        - asset: assets/fonts/Custom.ttf
        
          
 

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
