name: FSOUNotes
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
# //publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.1.0+41

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI / Widget Packages
  pimp_my_button: ^1.0.0
  flutter_intro: ^0.7.0
  charts_flutter: ^0.9.0
  awesome_dialog: ^1.1.3
  cupertino_icons: ^0.1.3
  direct_select_flutter: ^1.0.6
  dynamic_text_highlighting: ^2.2.0
  expansion_tile_card: ^1.0.3
  flutter_auth_buttons: ^0.6.0
  flutter_material_pickers: ^1.7.3
  fluttertoast: ^4.0.1
  font_awesome_flutter: ^8.8.1
  lottie: ^0.4.1
  material_design_icons_flutter: ^4.0.5755
  shimmer: ^1.1.1
  modal_progress_hud: ^0.1.3
  cached_network_image: ^2.2.0+1
  day_night_switcher: ^0.1.1+1

  # Utility Packages [ packages to perform a simple task ]
  cuid: ^0.1.2
  file_picker: ^1.12.0
  flutter_full_pdf_viewer: ^1.0.6
  flutter_dotenv: ^2.1.0
  flutter_mailer: ^0.5.1
  flutter_secure_storage: ^3.3.1+1
  flutter_typeahead: ^1.8.1
  flutter_webview_plugin: ^0.3.11
  image_picker: ^0.6.7+2
  in_app_review: ^1.0.3
  intl: ^0.16.1
  logger: ^0.6.0
  url_launcher: ^5.4.11
  open_appstore: ^1.0.2
  package_info: ^0.4.0+16
  path_provider: ^1.6.11
  permission_handler: ^5.0.1+1
  share: ^0.6.4+3
  feature_discovery: ^0.12.1
  connectivity_wrapper: ^1.0.4
  flutter_windowmanager: ^0.0.2
  disable_screenshots: ^0.1.0
  rate_my_app: ^0.7.2
  substring_highlight: ^0.1.2
  syncfusion_flutter_pdfviewer: ^18.4.32-beta
  syncfusion_flutter_pdf: ^18.4.32-beta
  syncfusion_flutter_sliders: ^18.4.32-beta
  flutter_downloader: ^1.5.2
  open_file: ^3.0.3
  ext_storage: ^1.0.3
  confetti: ^0.5.4+1
  # flutter_easyloading: ^2.2.2

  # Architecture related packages
  flutter_hooks: null
  auto_route: ^0.5.0
  get_it: null
  injectable: null
  observable_ish: null
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  stacked: 1.6.0
  stacked_hooks: 0.1.1+3
  stacked_services: ^0.6.0+1
  shared_preferences: ^0.5.7+3
  # purchases_flutter: ^2.0.0
  awesome_notifications: any

  # firebase/google packages
  cloud_firestore: ^0.13.7
  firebase_admob: ^0.9.3
  firebase_analytics: 5.0.0
  firebase_auth: ^0.16.1
  firebase_remote_config: 0.3.1+1
  firebase_storage: ^3.1.6
  google_sign_in: ^4.5.1
  googleapis: ^0.54.0
  googleapis_auth: ^0.2.11
  firebase_messaging: 6.0.16
  in_app_purchase: ^0.3.4+16

  # packages of other services being used
  onesignal_flutter: ^2.6.1
  sentry: ">=3.0.0 <4.0.0"
  wiredash: ^0.4.0

  # Miscellaneous Packages
  async: ^2.0.8
  http: ^0.12.0+2
  mime: ^0.9.6+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: null
  hive_generator: ^0.8.2
  build_runner: null
  flutter_launcher_icons: "^0.7.3"
  injectable_generator: null
  mockito: null

flutter_icons:
  image_path: "assets/images/apnaicon.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/study1.jpg
    - assets/images/study2.jpg
    - assets/images/study3.jpg
    - assets/images/study4.jpg
    - assets/images/study5.jpg
    - assets/lottie/
    - .env

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Custom
      fonts:
        - asset: assets/fonts/Custom.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
