name: FSOUNotes
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
# //publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.1.0+41

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI / Widget Packages
  pimp_my_button: ^1.0.0
  flutter_intro: ^2.1.0
  awesome_dialog: ^2.0.0-nullsafety.1
  cupertino_icons: ^1.0.2
  direct_select_flutter: ^1.1.0
  dynamic_text_highlighting: ^2.2.0
  expansion_tile_card: ^2.0.0
  flutter_auth_buttons: ^0.6.0
  flutter_material_pickers: ^2.1.1
  fluttertoast: ^8.0.6
  font_awesome_flutter: ^9.0.0
  lottie: ^1.0.1
  material_design_icons_flutter: ^5.0.5955-rc.1
  shimmer: ^2.0.0
  modal_progress_hud: ^0.1.3
  cached_network_image: ^3.0.0
  day_night_switcher: ^0.2.0+1

  # Utility Packages [ packages to perform a simple task ]
  cuid: ^0.1.2
  file_picker: ^3.0.1
  flutter_full_pdf_viewer: ^1.0.6
  flutter_dotenv: ^4.0.0-nullsafety.0
  flutter_mailer: ^2.0.0-null-safe
  flutter_secure_storage: ^4.1.0
  flutter_typeahead: ^3.1.1
  flutter_webview_plugin: ^0.3.11
  image_picker: ^0.7.4
  in_app_review: ^2.0.2
  intl: ^0.17.0
  logger: ^1.0.0
  url_launcher: ^6.0.3
  open_appstore: ^1.0.2
  package_info: ^2.0.0
  path_provider: ^2.0.1
  permission_handler: ^7.0.0
  share: ^2.0.1
  feature_discovery: ^0.14.0
  connectivity_wrapper: ^1.0.5
  flutter_windowmanager: ^0.0.2
  disable_screenshots: ^0.1.0
  rate_my_app: ^1.1.0+1
  substring_highlight: ^1.0.26
  syncfusion_flutter_pdfviewer: ^19.1.57-beta
  syncfusion_flutter_pdf: ^19.1.57-beta
  syncfusion_flutter_sliders: ^19.1.57-beta
  syncfusion_flutter_charts: ^19.1.57+1
  flutter_downloader: ^1.6.0
  open_file: ^3.2.0
  ext_storage: ^1.0.3
  confetti: ^0.6.0-nullsafety
  # flutter_easyloading: ^2.2.2

  # Architecture related packages
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  stacked: ^2.1.0
  stacked_services: ^0.8.5
  shared_preferences: ^2.0.5
  # purchases_flutter: ^2.0.0
  awesome_notifications: ^0.0.6+1

  # firebase/google packages
  cloud_firestore: ^1.0.6
  google_mobile_ads: ^0.12.1+1
  firebase_analytics: ^8.0.1
  firebase_auth: ^1.1.1
  firebase_remote_config: ^0.10.0-dev.1
  firebase_storage: ^8.0.4
  google_sign_in: ^5.0.2
  googleapis: ^2.0.0
  googleapis_auth: ^1.1.0
  firebase_messaging: ^9.1.2
  in_app_purchase: ^0.5.2

  # packages of other services being used
  onesignal_flutter: ^3.0.0-beta2
  sentry: ^5.0.0
  wiredash: ^0.6.2

  # Miscellaneous Packages
  async: ^2.5.0
  http: ^0.13.1
  mime: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^2.0.0
  hive_generator: ^1.1.0
  build_runner: ^2.0.1
  stacked_generator:
  flutter_launcher_icons: ^0.9.0
  mockito: ^5.0.5

flutter_icons:
  image_path: "assets/images/apnaicon.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/study1.jpg
    - assets/images/study2.jpg
    - assets/images/study3.jpg
    - assets/images/study4.jpg
    - assets/images/study5.jpg
    - assets/lottie/
    - .env

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Custom
      fonts:
        - asset: assets/fonts/Custom.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages