name: FSOUNotes
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
# //publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.1.0+25

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.0.8
  auto_route: ^0.5.0
  awesome_dialog: ^1.1.3
  cached_network_image: ^2.2.0+1
  charts_flutter: ^0.9.0
  cloud_firestore: ^0.13.7
  cuid: ^0.1.2
  cupertino_icons: ^0.1.3
  direct_select_flutter: ^1.0.6
  dynamic_text_highlighting: ^2.2.0
  expansion_tile_card: ^1.0.3
  file_picker: ^1.12.0
  firebase_admob: ^0.9.3
  firebase_analytics: 5.0.0
  firebase_auth: ^0.16.1
  firebase_remote_config: 0.3.1+1
  firebase_storage: ^3.1.6
  flutter_auth_buttons: ^0.6.0
  flutter_dotenv: ^2.1.0
  flutter_full_pdf_viewer: ^1.0.6
  flutter_hooks: null
  flutter_mailer: ^0.5.1
  flutter_material_pickers: ^1.7.3
  flutter_secure_storage: ^3.3.1+1
  flutter_typeahead: ^1.8.1
  flutter_webview_plugin: ^0.3.11
  flutter_windowmanager: ^0.0.2
  fluttertoast: ^4.0.1
  font_awesome_flutter: ^8.8.1
  get_it: null
  google_sign_in: ^4.5.1
  googleapis: ^0.54.0
  googleapis_auth: ^0.2.11
  http: ^0.12.0+2
  image_picker: ^0.6.7+2
  in_app_review: ^1.0.3
  injectable: null
  intl: ^0.16.1
  kf_drawer: ^1.1.2
  logger: ^0.6.0
  lottie: ^0.4.1
  material_design_icons_flutter: ^4.0.5755
  mime: ^0.9.6+3
  modal_progress_hud: ^0.1.3
  observable_ish: null
  onesignal_flutter: ^2.6.1
  open_appstore: ^1.0.2
  package_info: ^0.4.0+16
  path_provider: ^1.6.11
  permission_handler: ^5.0.1+1
  sentry: ">=3.0.0 <4.0.0"
  share: ^0.6.4+3
  shared_preferences: ^0.5.7+3
  shimmer: ^1.1.1
  stacked: 1.6.0
  stacked_hooks: 0.1.1+3
  stacked_services: 0.4.4+1
  url_launcher: ^5.4.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: null

  build_runner: null
  flutter_launcher_icons: "^0.7.3"
  injectable_generator: null
  mockito: null

flutter_icons:
  image_path: "assets/images/apnaicon.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/study1.jpg
    - assets/images/study2.jpg
    - assets/images/study3.jpg
    - assets/images/study4.jpg
    - assets/images/study5.jpg
    - assets/lottie/
    - .env

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Custom
      fonts:
        - asset: assets/fonts/Custom.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
