import 'package:FSOUNotes/ui/views/FilterDocuments/FD_DocumentDisplay/fd_documentview.dart';
import 'package:FSOUNotes/ui/views/FilterDocuments/FD_InputScreen/fd_inputView.dart';
import 'package:FSOUNotes/ui/views/FilterDocuments/FD_subjectdisplay/fd_subjectview.dart';
import 'package:FSOUNotes/ui/views/Settings/settings_view.dart';
import 'package:FSOUNotes/ui/views/about_us/privacy_policy/privacy_policyview.dart';
import 'package:FSOUNotes/ui/views/about_us/privacy_policy/terms_and_conditionview.dart';
import 'package:FSOUNotes/ui/views/admin/admin_view.dart';
import 'package:FSOUNotes/ui/views/admin/upload_log/upload_log_detail/upload_log_detail_view.dart';
import 'package:FSOUNotes/ui/views/admin/upload_log/upload_log_view.dart';
import 'package:FSOUNotes/ui/views/admin/upload_log/upload_log_detail/upload_log_edit/upload_log_edit_view.dart';
import 'package:FSOUNotes/ui/views/all_documents/all_documents_view.dart';
import 'package:FSOUNotes/ui/views/downloads/Downloads_view.dart';
import 'package:FSOUNotes/ui/views/edit/edit_view.dart';
import 'package:FSOUNotes/ui/views/home/home_view.dart';
import 'package:FSOUNotes/ui/views/intro/intro_view.dart';
import 'package:FSOUNotes/ui/views/links/links_view.dart';
import 'package:FSOUNotes/ui/views/notes/notes_view.dart';
import 'package:FSOUNotes/ui/views/pdf/pdf_view.dart';
import 'package:FSOUNotes/ui/views/question_papers/question_papers_view.dart';
import 'package:FSOUNotes/ui/views/splash/spash_view.dart';
import 'package:FSOUNotes/ui/views/syllabus/syllabus_view.dart';
import 'package:FSOUNotes/ui/views/upload/upload_selection/upload_selection_view.dart';
import 'package:FSOUNotes/ui/views/upload/upload_view.dart';
import 'package:FSOUNotes/ui/views/web_view/web_view.dart';
import 'package:FSOUNotes/ui/widgets/smart_widgets/thank_you_page/thank_you_view.dart';
import 'package:FSOUNotes/ui/widgets/smart_widgets/thank_you_page/upload_thank_you/thank_you_for_uploading.dart';
import 'package:FSOUNotes/ui/widgets/smart_widgets/watch_ad/watch_ad_view.dart';
import 'package:FSOUNotes/ui/widgets/smart_widgets/why_to_pay_for_download_page/why_to_pay_for_download.dart';
import 'package:auto_route/auto_route_annotations.dart';
import 'package:FSOUNotes/ui/views/about_us/about_us_view.dart';

@MaterialAutoRouter()
class $Router {
  @initial
  SplashView splashViewRoute;
  IntroView introViewRoute;
  HomeView homeViewRoute;
  AllDocumentsView allDocumentsViewRoute;
  PDFScreen pdfScreenRoute;
  NotesView notesViewRoute;
  QuestionPapersView questionPapersViewRoute;
  SyllabusView syllabusViewRoute;
  LinksView linksViewRoute;
  AboutUsView aboutUsViewRoute;
  SettingsView profileView;
  UploadView uploadViewRoute;
  UploadSelectionView uploadSelectionViewRoute;
  DownLoadView downLoadView;
  FDInputView fdInputView;
  FDSubjectView fdSubjectView;
  FDDocumentView fdDocumentView;
  PrivacyPolicyView privacyPolicyView;
  TermsAndConditionView termsAndConditionView;
  AdminView adminViewRoute;
  WebViewWidget webViewWidgetRoute;
  EditView editViewRoute;
  UploadLogView uploadLogViewRoute;
  UploadLogDetailView uploadLogDetailViewRoute;
  UploadLogEditView uploadLogEditViewRoute;
  @MaterialRoute(fullscreenDialog: true)
  WatchAdToContinueView watchAdToContinueView;
  @MaterialRoute(fullscreenDialog: true)
  ThankYouView thankYouView;
  @MaterialRoute(fullscreenDialog: true)
  ThankYouForUploadingView thankYouForUploadingViewRoute;
  @MaterialRoute(fullscreenDialog: true)
  WhyToPayForDownloadView whyToPayForDownloadView;
}
